let sb=null,session=null,profile=null,spaces=[],currentSpace=null,rooms=[],currentRoom=null,realtime=null,lang=localStorage.getItem('luka-lang')||'ja',authMode='login',replyTo=null,aiHistory=[],callState=null;
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=(ja,en)=>lang==='ja'?ja:en;
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
async function api(path,opt){const r=await fetch(path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function boot(){
  $('lang').value=lang;
  const cfg=await api('/api/config');
  if(cfg.supabase.enabled&&window.supabase){sb=window.supabase.createClient(cfg.supabase.url,cfg.supabase.publishableKey);const g=await sb.auth.getSession();session=g.data.session;sb.auth.onAuthStateChange((_e,s)=>{session=s;if(s)enter();else showAuth()});if(session)await enter();else showAuth();}
  else{session={user:{id:'local-demo',email:'demo@luka.local'}};profile=JSON.parse(localStorage.getItem('luka-profile')||'null')||{id:'local-demo',display_name:'そら',username:'sora_0921',bio:'Luka demo',status:'online',avatar_url:null};await enter()}
}
function showAuth(){$('auth').classList.remove('hidden');$('shell').classList.add('hidden')}
async function enter(){if(!profile)await loadProfile();$('auth').classList.add('hidden');$('shell').classList.remove('hidden');await loadProfile();await loadSpaces();render()}
async function loadProfile(){if(sb&&session){let r=await sb.from('profiles').select('*').eq('id',session.user.id).maybeSingle();if(r.error)console.warn(r.error);profile=r.data||{id:session.user.id,display_name:session.user.user_metadata?.display_name||session.user.email.split('@')[0],username:(session.user.email.split('@')[0].replace(/[^a-zA-Z0-9_]/g,'_')+'_'+session.user.id.slice(0,6)).toLowerCase(),bio:'',status:'online',avatar_url:null};if(!r.data)await sb.from('profiles').upsert(profile)}else profile=profile||{id:'local-demo',display_name:'そら',username:'sora_0921',bio:'',status:'online',avatar_url:null};updateMe()}
function updateMe(){$('meName').textContent=profile.display_name||'Luka';$('meHandle').textContent='@'+String(profile.username||'').replace(/^@/,'');$('avatar').innerHTML=profile.avatar_url?`<img src="${esc(profile.avatar_url)}" alt="">`:(profile.display_name?.[0]||'L').toUpperCase()}
async function loadSpaces(){if(sb&&session){const r=await sb.from('spaces').select('*').order('created_at',{ascending:true});spaces=r.data||[];if(r.error)toast(r.error.message)}else spaces=JSON.parse(localStorage.getItem('luka-spaces')||'[]');renderSpaces()}
function renderSpaces(){$('spaces').innerHTML=spaces.map(s=>`<button class="space ${currentSpace&&currentSpace.id===s.id?'active':''}" onclick="openSpace('${esc(s.id)}')"><span class="space-icon">${s.icon_url?`<img src="${esc(s.icon_url)}">`:(s.name?.[0]||'✦')}</span><span class="grow">${esc(s.name)}</span></button>`).join('')}
function render(){if(currentSpace){renderSpace();return}const v=window.view||'home';({home,community,friends,dm,ai,bots,settings}[v]||home)();document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===v));}
function setHeader(t,c='Luka'){$('title').textContent=t;$('crumb').textContent=c}
function home(){$('content').innerHTML=`<div class="page"><div class="hero-card"><div class="eyebrow">LUKA / WORKSPACE</div><h1>${tr('あなたの世界を、つなげよう。','Connect your universe.')}</h1><p class="muted">${tr('スペース、リアルタイム会話、DM、AIをひとつに。','Spaces, realtime chat, DMs, and AI in one place.')}</p><button class="primary" onclick="createSpace()">＋ ${tr('スペースを作成','Create space')}</button></div><div class="grid"><div class="card"><h3>✦ Spaces</h3><p>${tr('コミュニティを作って部屋やメンバーを管理。','Build communities and organize rooms.')}</p></div><div class="card"><h3>◌ Realtime</h3><p>${tr('メッセージとリアクションをリアルタイム同期。','Sync messages and reactions in real time.')}</p></div><div class="card"><h3>◇ Luka AI</h3><p>${tr('公式AIに質問したりアイデアを整理。','Ask the official AI for help and ideas.')}</p></div></div></div>`;setHeader(tr('ホーム','Home'))}
async function community(){setHeader(tr('コミュニティ','Community'));$('content').innerHTML=`<div class="page"><div class="eyebrow">COMMUNITY HUB</div><h2>${tr('公開スペースを探す','Discover public spaces')}</h2><div class="search"><input id="communitySearch" class="input" placeholder="${tr('名前で検索…','Search by name…')}" oninput="renderCommunityList()"></div><div id="communityList" class="grid"></div></div>`;renderCommunityList()}
function renderCommunityList(){const q=($('communitySearch')?.value||'').toLowerCase();const list=spaces.filter(s=>!s.invite_only&&s.name.toLowerCase().includes(q));$('communityList').innerHTML=list.map(s=>`<div class="card"><div class="profile-row"><div class="avatar">${s.icon_url?`<img src="${esc(s.icon_url)}">`:(s.name?.[0]||'✦')}</div><div class="grow"><h3>${esc(s.name)}</h3><p>Public space</p></div></div><button class="primary" onclick="joinSpace('${esc(s.id)}')">${tr('参加','Join')}</button></div>`).join('')||`<div class="card"><p>${tr('見つかりませんでした。','No public spaces found.')}</p></div>`}
async function joinSpace(id){if(!sb)return toast(tr('デモモードではそのまま開けます。','Demo mode opens it directly.'));const r=await sb.from('space_members').upsert({space_id:id,user_id:session.user.id,role:'member'});if(r.error)return toast(r.error.message);toast(tr('参加しました','Joined'));await loadSpaces();openSpace(id)}
async function openSpace(id){currentSpace=spaces.find(s=>String(s.id)===String(id));window.view=null;replyTo=null;if(!currentSpace)return;await loadRooms();renderSpaces();renderSpace()}
async function loadRooms(){if(!currentSpace)return;if(sb){let r=await sb.from('rooms').select('*').eq('space_id',currentSpace.id).order('created_at');rooms=r.data||[];if(!rooms.length){const c=await sb.from('rooms').insert({space_id:currentSpace.id,name:'general'}).select().single();if(c.data)rooms=[c.data]}}else{rooms=JSON.parse(localStorage.getItem('luka-rooms')||'[]').filter(x=>x.space_id===currentSpace.id);if(!rooms.length){rooms=[{id:'room-'+Date.now(),space_id:currentSpace.id,name:'general'}];localStorage.setItem('luka-rooms',JSON.stringify(JSON.parse(localStorage.getItem('luka-rooms')||'[]').concat(rooms)))}}currentRoom=rooms.find(r=>r.id===currentRoom?.id)||rooms[0]}
async function renderSpace(){if(!currentSpace)return;setHeader(currentSpace.name,'Space');let msgs=[];if(sb&&currentRoom){const r=await sb.from('messages').select('id,content,created_at,user_id,edited').eq('room_id',currentRoom.id).order('created_at');msgs=r.data||[];}else if(currentRoom){msgs=JSON.parse(localStorage.getItem('luka-local-msgs')||'[]').filter(x=>x.room_id===currentRoom.id);}
const banner=currentSpace.banner_url?`style="background-image:url('${esc(currentSpace.banner_url)}')"`:'';$('content').innerHTML=`<div class="page"><div class="space-banner" ${banner}><div class="banner-info"><b>${esc(currentSpace.name)}</b><div class="muted">${currentSpace.invite_only?'Private':'Public'} · ${currentSpace.owner_id===session.user.id?'Owner':'Member'}</div></div></div><div class="room-tabs">${rooms.map(r=>`<button class="room-tab ${r.id===currentRoom?.id?'active':''}" onclick="switchRoom('${esc(r.id)}')"># ${esc(r.name)}</button>`).join('')}<button class="room-tab" onclick="createRoom()">＋</button><button class="room-tab" onclick="spaceSettings()">⚙</button><button class="room-tab" onclick="startCall()">☎ ${tr('通話','Call')}</button></div><div class="chat"><div class="messages" id="messages">${msgs.map(messageHtml).join('')}</div>${replyTo?`<div class="replybar">↩ ${tr('返信先','Replying to')} ${esc(replyTo.content.slice(0,70))} <button class="mini" onclick="replyTo=null;renderSpace()">×</button></div>`:''}<div class="composer"><input id="message" class="input" placeholder="${tr('メッセージを入力…','Write a message…')}" onkeydown="if(event.key==='Enter')sendMessage()"><button class="primary" onclick="sendMessage()">↗</button></div></div></div>`;subscribeRoom();scrollMessages()}
function messageHtml(m){const mine=m.user_id===session?.user?.id;return `<div class="msg ${mine?'mine':''}" data-mid="${esc(m.id)}"><div class="msg-head"><b>${mine?esc(profile.display_name):'User'}</b><small>${new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}${m.edited?' · edited':''}</small></div><div class="msg-body">${esc(m.content)}</div><div class="msg-tools"><button class="mini" onclick="setReply('${esc(m.id)}')">↩ ${tr('返信','Reply')}</button>${mine?`<button class="mini" onclick="editMessage('${esc(m.id)}')">${tr('編集','Edit')}</button><button class="mini" onclick="deleteMessage('${esc(m.id)}')">${tr('削除','Delete')}</button>`:''}</div><div class="reactions"><button class="reaction" onclick="react('${esc(m.id)}','👍')">👍</button><button class="reaction" onclick="react('${esc(m.id)}','❤️')">❤️</button><button class="reaction" onclick="react('${esc(m.id)}','✨')">✨</button><button class="reaction" onclick="showCustomReactions('${esc(m.id)}')">＋</button></div></div>`}
function scrollMessages(){const m=$('messages');if(m)m.scrollTop=m.scrollHeight}
function subscribeRoom(){if(!sb||!currentRoom)return;if(realtime)sb.removeChannel(realtime);realtime=sb.channel('room-'+currentRoom.id).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`room_id=eq.${currentRoom.id}`},async p=>{if(p.eventType==='INSERT'){const box=$('messages');if(box&&!box.querySelector(`[data-mid=\"${p.new.id}\"]`)){box.insertAdjacentHTML('beforeend',messageHtml(p.new));scrollMessages()}}else renderSpace()}).on('postgres_changes',{event:'*',schema:'public',table:'reactions'},()=>renderSpace()).subscribe()}
async function switchRoom(id){currentRoom=rooms.find(r=>r.id===id);await renderSpace()}
async function sendMessage(){const i=$('message'),text=i?.value.trim();if(!text)return;if(text.startsWith('/')){return botCommand(text)}if(sb){const r=await sb.from('messages').insert({room_id:currentRoom.id,user_id:session.user.id,content:replyTo?`↩ ${replyTo.content}\n${text}`:text});if(r.error)return toast(r.error.message)}else{const a=JSON.parse(localStorage.getItem('luka-local-msgs')||'[]');a.push({id:'m-'+Date.now(),room_id:currentRoom.id,user_id:'local-demo',content:text,created_at:new Date().toISOString()});localStorage.setItem('luka-local-msgs',JSON.stringify(a))}i.value='';replyTo=null;if(!sb)renderSpace()}
async function editMessage(id){if(!sb)return toast(tr('デモでは編集保存を省略しています。','Editing is disabled in demo mode.'));const old=await sb.from('messages').select('content').eq('id',id).single();if(old.error)return toast(old.error.message);const text=prompt(tr('新しい内容','New content'),old.data.content);if(text===null)return;const r=await sb.from('messages').update({content:text,edited:true}).eq('id',id).eq('user_id',session.user.id);if(r.error)toast(r.error.message);else renderSpace()}
async function deleteMessage(id){if(!sb)return toast(tr('デモでは削除保存を省略しています。','Delete is disabled in demo mode.'));if(!confirm(tr('このメッセージを削除しますか？','Delete this message?')))return;const r=await sb.from('messages').delete().eq('id',id).eq('user_id',session.user.id);if(r.error)toast(r.error.message);else renderSpace()}
function setReply(id){const e=document.querySelector(`[data-mid="${id}"] .msg-body`);replyTo={id,content:e?.textContent||''};renderSpace()}
async function react(messageId,emoji){if(!sb)return toast(emoji);const r=await sb.from('reactions').upsert({message_id:messageId,user_id:session.user.id,emoji},{onConflict:'message_id,user_id,emoji'});if(r.error)toast(r.error.message)}
async function createRoom(){if(!currentSpace)return;const name=prompt(tr('部屋名','Room name'),'general-2');if(!name)return;if(sb){const r=await sb.from('rooms').insert({space_id:currentSpace.id,name}).select().single();if(r.error)return toast(r.error.message);rooms.push(r.data);currentRoom=r.data}else{const r={id:'room-'+Date.now(),space_id:currentSpace.id,name};rooms.push(r);localStorage.setItem('luka-rooms',JSON.stringify(JSON.parse(localStorage.getItem('luka-rooms')||'[]').concat(r)));currentRoom=r}renderSpace()}
async function createSpace(){const name=prompt(tr('スペース名','Space name'));if(!name)return;if(sb){const r=await sb.from('spaces').insert({name,owner_id:session.user.id,invite_only:false}).select().single();if(r.error)return toast(r.error.message);await sb.from('space_members').upsert({space_id:r.data.id,user_id:session.user.id,role:'owner'});spaces.push(r.data);await loadSpaces();openSpace(r.data.id)}else{const s={id:'space-'+Date.now(),name,owner_id:'local-demo',invite_only:false,icon_url:null,banner_url:null};spaces.push(s);localStorage.setItem('luka-spaces',JSON.stringify(spaces));renderSpaces();openSpace(s.id)}}
function profileModal(){showModal(tr('プロフィール','Profile'),`<div class="profile-row"><div id="modalAvatar" class="avatar profile-big">${profile.avatar_url?`<img src="${esc(profile.avatar_url)}">`:(profile.display_name?.[0]||'L')}</div><div><b>${esc(profile.display_name)}</b><div class="muted">@${esc(profile.username)}</div></div></div><input id="pn" class="input" value="${esc(profile.display_name||'')}" placeholder="Display name"><input id="pu" class="input" value="${esc(profile.username||'')}" placeholder="Username"><input id="pb" class="input" value="${esc(profile.bio||'')}" placeholder="Bio"><label class="muted">Avatar<input id="pa" class="input" type="file" accept="image/*"></label><select id="ps" class="input"><option value="online">online</option><option value="away">away</option><option value="busy">busy</option><option value="invisible">invisible</option></select>`,tr('保存','Save'),saveProfile);setTimeout(()=>{$('ps').value=profile.status||'online'},0)}
async function saveProfile(){let avatar=profile.avatar_url||null;const f=$('pa')?.files?.[0];if(f&&sb){const ext=(f.name.split('.').pop()||'png').toLowerCase();const p=`${session.user.id}/${Date.now()}.${ext}`;const u=await sb.storage.from('avatars').upload(p,f,{upsert:false,contentType:f.type});if(u.error)return toast(u.error.message);avatar=sb.storage.from('avatars').getPublicUrl(p).data.publicUrl}profile={...profile,display_name:$('pn').value.trim()||profile.display_name,username:$('pu').value.replace(/^@/,'').trim()||profile.username,bio:$('pb').value,status:$('ps').value,avatar_url:avatar};if(sb){const r=await sb.from('profiles').update(profile).eq('id',session.user.id);if(r.error)return toast(r.error.message)}else localStorage.setItem('luka-profile',JSON.stringify(profile));closeModal();updateMe();toast(tr('保存しました','Saved'))}
function spaceSettings(){if(currentSpace.owner_id!==session.user.id)return toast(tr('スペース所有者のみ変更できます。','Only the owner can edit this space.'));showModal(tr('スペース設定','Space settings'),`<input id="sn" class="input" value="${esc(currentSpace.name)}"><label>Icon<input id="si" class="input" type="file" accept="image/*"></label><label>Banner<input id="sbanner" class="input" type="file" accept="image/*"></label><label><input id="private" type="checkbox" ${currentSpace.invite_only?'checked':''}> ${tr('非公開スペース','Private space')}</label>`,tr('保存','Save'),saveSpace)}
async function saveSpace(){let icon=currentSpace.icon_url||null,banner=currentSpace.banner_url||null;for(const [id,bucket,prefix] of [['si','space-assets','icon'],['sbanner','space-assets','banner']]){const f=$(id)?.files?.[0];if(f&&sb){const ext=(f.name.split('.').pop()||'png').toLowerCase();const p=`${session.user.id}/${currentSpace.id}/${prefix}-${Date.now()}.${ext}`;const u=await sb.storage.from(bucket).upload(p,f,{contentType:f.type});if(u.error)return toast(u.error.message);const pub=sb.storage.from(bucket).getPublicUrl(p).data.publicUrl;if(prefix==='icon')icon=pub;else banner=pub}}currentSpace={...currentSpace,name:$('sn').value.trim()||currentSpace.name,icon_url:icon,banner_url:banner,invite_only:$('private').checked};if(sb){const r=await sb.from('spaces').update({name:currentSpace.name,icon_url:icon,banner_url:banner,invite_only:currentSpace.invite_only}).eq('id',currentSpace.id).eq('owner_id',session.user.id);if(r.error)return toast(r.error.message)}else{spaces=spaces.map(x=>x.id===currentSpace.id?currentSpace:x);localStorage.setItem('luka-spaces',JSON.stringify(spaces))}await loadSpaces();closeModal();renderSpace()}
async function customReactionUpload(){if(!sb)return toast(tr('Supabase接続が必要です。','Supabase is required.'));const f=$('crfile').files[0],name=$('crname').value.trim();if(!f||!name)return;const ext=(f.name.split('.').pop()||'png').toLowerCase(),p=`${session.user.id}/${Date.now()}.${ext}`;const u=await sb.storage.from('custom-reactions').upload(p,f,{contentType:f.type});if(u.error)return toast(u.error.message);const url=sb.storage.from('custom-reactions').getPublicUrl(p).data.publicUrl;const r=await sb.from('custom_reactions').insert({name,image_url:url,creator_id:session.user.id});if(r.error)return toast(r.error.message);closeModal();toast(tr('リアクションを追加しました','Reaction added'))}
async function showCustomReactions(messageId){if(!sb)return showModal('Custom reactions','<p class="muted">Supabase mode is required for custom images.</p><button class="primary" onclick="customReactionModal()">Create one</button>','OK',closeModal);const r=await sb.from('custom_reactions').select('*').order('created_at',{ascending:false}).limit(30);const items=r.data||[];showModal(tr('カスタムリアクション','Custom reactions'),`<div class="reactions">${items.map(x=>`<button class="reaction" onclick="reactCustom('${esc(messageId)}','${esc(x.id)}')"><img src="${esc(x.image_url)}" style="width:24px;height:24px;object-fit:contain;vertical-align:middle"> ${esc(x.name)}</button>`).join('')}</div><hr><button class="primary" onclick="customReactionModal()">＋ ${tr('作成','Create')}</button>`,'',closeModal)}
async function reactCustom(messageId,id){const r=await sb.from('custom_reactions').select('image_url').eq('id',id).single();if(r.error)return toast(r.error.message);await react(messageId,`custom:${r.data.image_url}`);closeModal()}
function customReactionModal(){showModal(tr('カスタムリアクションを作成','Create custom reaction'),`<input id="crname" class="input" placeholder="Name"><input id="crfile" class="input" type="file" accept="image/*">`,tr('追加','Add'),customReactionUpload)}
function ai(){setHeader('Luka AI');$('content').innerHTML=`<div class="page"><div class="eyebrow">LUKA AI</div><h2>${tr('Lukaに聞く','Ask Luka')}</h2><div id="aiList" class="messages" style="height:58vh"></div><div class="composer"><input id="aiInput" class="input" placeholder="${tr('質問を入力…','Ask something…')}" onkeydown="if(event.key==='Enter')askAI()"><button class="primary" onclick="askAI()">↗</button></div></div>`;if(!aiHistory.length)$('aiList').innerHTML='<div class="msg"><b>Luka</b><div>'+tr('こんにちは！何を手伝おうか？','Hi! What can I help you with?')+'</div></div>';else aiHistory.forEach(x=>addAI(x.role,x.content))}
function addAI(role,text){$('aiList')?.insertAdjacentHTML('beforeend',`<div class="msg ${role==='user'?'mine':''}"><b>${role==='user'?esc(profile.display_name):'Luka'}</b><div class="msg-body">${esc(text)}</div></div>`);scrollMessages()}
async function askAI(){const i=$('aiInput'),m=i?.value.trim();if(!m)return;i.value='';addAI('user',m);aiHistory.push({role:'user',content:m});try{const d=await api('/api/luka-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:m,conversation:aiHistory})});addAI('assistant',d.reply);aiHistory.push({role:'assistant',content:d.reply})}catch(e){addAI('assistant',e.message);toast(e.message)}}
function friends(){setHeader(tr('フレンド','Friends'));$('content').innerHTML=`<div class="page"><div class="eyebrow">PEOPLE</div><h2>${tr('フレンド','Friends')}</h2><div class="card"><p>${tr('ユーザー名で追加できます。DB版ではフレンドテーブルを利用します。','Add people by username. The DB version uses the friends table.')}</p><div class="search"><input id="friendSearch" class="input" placeholder="@username"><button class="primary" onclick="addFriend()">＋</button></div></div><div class="card" style="margin-top:14px"><h3>${tr('フレンド一覧','Friend list')}</h3><div id="friendList"></div></div></div>`;loadFriends()}
async function loadFriends(){if(!sb){$('friendList').innerHTML='<p class="muted">Demo mode</p>';return}const r=await sb.from('friendships').select('id,status,friend_id,profiles!friendships_friend_id_fkey(id,display_name,username,avatar_url)').or(`user_id.eq.${session.user.id},friend_id.eq.${session.user.id}`);if(r.error){$('friendList').innerHTML=`<p class="muted">${esc(r.error.message)}</p>`;return}$('friendList').innerHTML=(r.data||[]).map(x=>`<div class="profile-row" style="padding:10px 0"><div class="avatar">${x.profiles?.avatar_url?`<img src="${esc(x.profiles.avatar_url)}">`:(x.profiles?.display_name?.[0]||'U')}</div><div class="grow"><b>${esc(x.profiles?.display_name||'User')}</b><small class="muted">@${esc(x.profiles?.username||'')}</small></div><span class="muted">${esc(x.status)}</span></div>`).join('')||'<p class="muted">No friends yet.</p>'}
async function addFriend(){if(!sb)return toast('Demo mode');const q=$('friendSearch').value.trim().replace(/^@/,'');if(!q)return;const r=await sb.from('profiles').select('id,display_name,username').eq('username',q).maybeSingle();if(r.error||!r.data)return toast(tr('ユーザーが見つかりません','User not found'));if(r.data.id===session.user.id)return toast(tr('自分自身は追加できません','You cannot add yourself'));const ins=await sb.from('friendships').insert({user_id:session.user.id,friend_id:r.data.id,status:'pending'});if(ins.error)return toast(ins.error.message);toast(tr('申請しました','Request sent'));loadFriends()}
async function dm(){setHeader('DM');$('content').innerHTML=`<div class="page"><div class="eyebrow">DIRECT MESSAGES</div><h2>DM</h2><div class="card"><p>${tr('フレンドとの1対1メッセージ。','One-to-one messages with friends.')}</p><div class="search"><input id="dmUser" class="input" placeholder="@username"><button class="primary" onclick="openDMByUsername()">開く</button></div></div><div id="dmList" class="grid"></div></div>`;loadDMs()}
async function loadDMs(){if(!sb){$('dmList').innerHTML='<div class="card"><p>Demo mode</p></div>';return}const r=await sb.from('dm_rooms').select('*').or(`user1_id.eq.${session.user.id},user2_id.eq.${session.user.id}`).order('created_at',{ascending:false});$('dmList').innerHTML=(r.data||[]).map(x=>`<div class="card"><p>${esc(x.user1_id===session.user.id?x.user2_id:x.user1_id)}</p><button class="primary" onclick="openDM('${esc(x.id)}')">Open</button></div>`).join('')||'<div class="card"><p class="muted">No DMs yet.</p></div>'}
async function openDMByUsername(){if(!sb)return toast('Supabase mode required');const q=$('dmUser').value.trim().replace(/^@/,'');const u=await sb.from('profiles').select('id,display_name,username').eq('username',q).maybeSingle();if(u.error||!u.data)return toast(tr('ユーザーが見つかりません','User not found'));let r=await sb.from('dm_rooms').select('*').or(`and(user1_id.eq.${session.user.id},user2_id.eq.${u.data.id}),and(user1_id.eq.${u.data.id},user2_id.eq.${session.user.id})`).maybeSingle();if(!r.data){r=await sb.from('dm_rooms').insert({user1_id:session.user.id,user2_id:u.data.id}).select().single()}if(r.error)return toast(r.error.message);openDM(r.data.id)}
async function openDM(id){if(!sb)return;const r=await sb.from('dm_messages').select('*').eq('dm_id',id).order('created_at');showModal('DM',`<div id="dmMsgs" class="messages" style="height:45vh">${(r.data||[]).map(x=>`<div class="msg ${x.sender_id===session.user.id?'mine':''}">${esc(x.content)}</div>`).join('')}</div><div class="composer"><input id="dmInput" class="input" onkeydown="if(event.key==='Enter')sendDM('${esc(id)}')"><button class="primary" onclick="sendDM('${esc(id)}')">↗</button></div>`,'',closeModal);}
async function sendDM(id){const text=$('dmInput').value.trim();if(!text)return;const r=await sb.from('dm_messages').insert({dm_id:id,sender_id:session.user.id,content:text});if(r.error)return toast(r.error.message);openDM(id)}
function bots(){setHeader('Bot Center');const bots=[['Luka Read','Read-aloud helper'],['Luka Poll','Create quick polls with /poll'],['Luka Reminder','Create local reminders with /remind'],['Luka Guard','Moderation helper concept'],['Luka AI Bot','Use /ai for the official AI']];$('content').innerHTML=`<div class="page"><div class="eyebrow">BOT CENTER</div><h2>${tr('Bot Center','Bot Center')}</h2><div class="grid">${bots.map(b=>`<div class="card"><h3>◇ ${b[0]}</h3><p>${b[1]}</p><button class="primary" onclick="toast('${esc(tr('このBotをスペースに追加しました','Bot added to this workspace'))}')">＋ Add</button></div>`).join('')}</div></div>`}
async function botCommand(text){const p=text.slice(1).split(' '),cmd=p.shift().toLowerCase(),arg=p.join(' ');if(cmd==='help')return toast('/poll /remind /roll /ai');if(cmd==='roll'){const n=Math.max(1,Math.min(100,Number(arg)||6));return postBot(`🎲 ${Math.floor(Math.random()*n)+1} / ${n}`)}if(cmd==='poll'){const opts=arg.split('|').map(x=>x.trim()).filter(Boolean);return postBot(`📊 ${opts.length?opts.join('  /  '):'Poll: add options with |'}`)}if(cmd==='remind'){return postBot(`⏰ ${arg||'Reminder created locally.'}`)}if(cmd==='ai'){try{const d=await api('/api/luka-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:arg||'Hello'})});return postBot(`◇ ${d.reply}`)}catch(e){return postBot(`◇ ${e.message}`)}}return toast(tr('不明なコマンド。/help を試してね。','Unknown command. Try /help.'))}
async function postBot(text){if(sb){const r=await sb.from('messages').insert({room_id:currentRoom.id,user_id:session.user.id,content:text});if(r.error)return toast(r.error.message)}else{const a=JSON.parse(localStorage.getItem('luka-local-msgs')||'[]');a.push({id:'m-'+Date.now(),room_id:currentRoom.id,user_id:'local-demo',content:text,created_at:new Date().toISOString()});localStorage.setItem('luka-local-msgs',JSON.stringify(a));renderSpace()}}
function showModal(title,body,ok,fn){$('modal').className='modal';$('modal').innerHTML=`<div class="modalbox"><h3>${title}</h3>${body}<div class="modal-actions"><button onclick="closeModal()">${tr('閉じる','Close')}</button>${ok?`<button id="modalOk" class="primary">${ok}</button>`:''}</div></div>`;if(ok)$('modalOk').onclick=fn}
function closeModal(){$('modal').className='hidden';$('modal').innerHTML=''}
async function settings(){setHeader(tr('設定','Settings'));const h=await api('/api/health');$('content').innerHTML=`<div class="page"><div class="eyebrow">SETTINGS</div><h2>${tr('設定','Settings')}</h2><div class="card"><h3>${tr('アカウント','Account')}</h3><p>${esc(profile.display_name)} · @${esc(profile.username)}</p><button class="primary" onclick="profileModal()">${tr('プロフィールを編集','Edit profile')}</button></div><div class="card" style="margin-top:14px"><h3>Server</h3><p class="muted">Luka ${h.version} · DB ${h.database} · AI ${h.ai?'ready':'not configured'} · Realtime ${h.realtime?'ready':'off'}</p></div></div>`}
function customNav(){currentSpace=null;replyTo=null;window.view=this.dataset.view;render()}
async function startCall(){if(!currentRoom)return;const roomKey='call-'+currentRoom.id;const layer=$('callLayer');layer.className='call';layer.innerHTML=`<div class="call-head"><b>☎ ${esc(currentSpace.name)} / #${esc(currentRoom.name)}</b><button onclick="endCall()">×</button></div><div class="videos" id="videos"></div><div class="call-controls"><button id="muteBtn" onclick="toggleMute()">🎙</button><button id="camBtn" onclick="toggleCam()">📷</button><button onclick="shareScreen()">▣</button><button class="danger" onclick="endCall()">${tr('退出','Leave')}</button></div>`;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:true});callState={stream,channel:sb?sb.channel(roomKey):null,peers:new Map(),muted:false,cam:true,id:crypto.randomUUID()};addVideo(callState.id,stream,profile.display_name,true);if(callState.channel){callState.channel.on('broadcast',{event:'call-signal'},async p=>{if(p.payload?.from===callState.id)return;await handleSignal(p.payload)}).subscribe(async status=>{if(status==='SUBSCRIBED')await callState.channel.send({type:'broadcast',event:'call-signal',payload:{type:'hello',from:callState.id,name:profile.display_name}})});}else toast(tr('通話の共有信号はSupabase接続時に有効です。','Call signaling needs Supabase.'))}catch(e){toast(e.message);endCall()}}
function addVideo(id,stream,name,local=false){const box=$('videos');if(!box)return;const tile=document.createElement('div');tile.className='video-tile';tile.id='video-'+id;tile.innerHTML=`<video ${local?'muted':''} autoplay playsinline></video><div class="video-label">${esc(name||'User')}</div>`;tile.querySelector('video').srcObject=stream;box.appendChild(tile)}
async function handleSignal(p){if(!callState)return;if(p.type==='hello'){const pc=makePeer(p.from,p.name);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await callState.channel.send({type:'broadcast',event:'call-signal',payload:{type:'offer',from:callState.id,to:p.from,name:profile.display_name,description:offer}})}else if(p.to!==callState.id)return;else if(p.type==='offer'){const pc=makePeer(p.from,p.name);await pc.setRemoteDescription(p.description);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await callState.channel.send({type:'broadcast',event:'call-signal',payload:{type:'answer',from:callState.id,to:p.from,name:profile.display_name,description:ans}})}else if(p.type==='answer'){const pc=callState.peers.get(p.from)?.pc;if(pc)await pc.setRemoteDescription(p.description)}else if(p.type==='ice'){const pc=callState.peers.get(p.from)?.pc;if(pc&&p.candidate)await pc.addIceCandidate(p.candidate)} }
function makePeer(id,name){if(callState.peers.has(id))return callState.peers.get(id).pc;const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});callState.stream.getTracks().forEach(t=>pc.addTrack(t,callState.stream));pc.onicecandidate=e=>{if(e.candidate)callState.channel.send({type:'broadcast',event:'call-signal',payload:{type:'ice',from:callState.id,to:id,candidate:e.candidate}})};pc.ontrack=e=>{if(!$('video-'+id))addVideo(id,e.streams[0],name,false)};callState.peers.set(id,{pc,name});return pc}
function toggleMute(){if(!callState)return;callState.muted=!callState.muted;callState.stream.getAudioTracks().forEach(t=>t.enabled=!callState.muted);$('muteBtn').textContent=callState.muted?'🔇':'🎙'}
function toggleCam(){if(!callState)return;callState.cam=!callState.cam;callState.stream.getVideoTracks().forEach(t=>t.enabled=callState.cam);$('camBtn').textContent=callState.cam?'📷':'🚫'}
async function shareScreen(){if(!callState)return;try{const s=await navigator.mediaDevices.getDisplayMedia({video:true});const track=s.getVideoTracks()[0];for(const {pc} of callState.peers.values()){const sender=pc.getSenders().find(x=>x.track?.kind==='video');if(sender)await sender.replaceTrack(track)}const local=$('video-'+callState.id)?.querySelector('video');if(local)local.srcObject=s;track.onended=()=>{const cam=callState.stream.getVideoTracks()[0];for(const {pc} of callState.peers.values()){const sender=pc.getSenders().find(x=>x.track?.kind==='video');if(sender)sender.replaceTrack(cam)}if(local)local.srcObject=callState.stream}}
catch(e){toast(e.message)}}
function endCall(){if(!callState){$('callLayer').className='hidden';return}callState.peers.forEach(x=>x.pc.close());callState.channel?.unsubscribe();callState.stream.getTracks().forEach(t=>t.stop());callState=null;$('callLayer').className='hidden';$('callLayer').innerHTML=''}
$('profileBtn').onclick=profileModal;$('settingsBtn').onclick=()=>{currentSpace=null;window.view='settings';render()};$('createSpace').onclick=createSpace;$('lang').onchange=e=>{lang=e.target.value;localStorage.setItem('luka-lang',lang);render()};$('logout').onclick=async()=>{if(sb)await sb.auth.signOut();else location.href='/'};$('callBtn').onclick=()=>currentRoom?startCall():toast(tr('スペースを開いてから通話してください。','Open a room before calling.'));document.querySelectorAll('.nav').forEach(n=>n.onclick=customNav);$('authSwitch').onclick=()=>{authMode=authMode==='login'?'signup':'login';$('authTitle').textContent=authMode==='login'?tr('Lukaへようこそ','Welcome to Luka'):tr('Lukaアカウントを作成','Create a Luka account');$('authGo').textContent=authMode==='login'?tr('ログイン','Log in'):tr('アカウントを作成','Create account');$('authSwitch').textContent=authMode==='login'?tr('アカウントを作成','Create account'):tr('ログインに戻る','Back to login');$('display').classList.toggle('hidden',authMode==='login')};$('authGo').onclick=async()=>{if(!sb){await enter();return}const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<6)return $('authMsg').textContent=tr('メールと6文字以上のパスワードを入力してください。','Enter an email and a password of at least 6 characters.');if(authMode==='login'){const r=await sb.auth.signInWithPassword({email,password});if(r.error)$('authMsg').textContent=r.error.message}else{const r=await sb.auth.signUp({email,password,options:{data:{display_name:$('display').value||email.split('@')[0]}}});if(r.error)$('authMsg').textContent=r.error.message;else $('authMsg').textContent=tr('確認メールを確認してください。','Check your confirmation email.')}};
boot();
