const $=x=>document.getElementById(x),socket=io();let token=localStorage.getItem("luka_token"),me,spaces,currentRoom,mode="login",page="home";
const api=(u,o={})=>{o.headers={...(o.headers||{}),"Content-Type":"application/json"};if(token)o.headers.Authorization="Bearer "+token;return fetch(u,o).then(async r=>{let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"通信エラー");return d})};const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));$("authSubmit").textContent=mode==="login"?"ログイン":"アカウントを作成"});
$("authForm").onsubmit=async e=>{e.preventDefault();try{let d=await api("/api/auth/"+mode,{method:"POST",body:JSON.stringify({username:$("username").value,password:$("password").value})});token=d.token;localStorage.setItem("luka_token",token);boot()}catch(e){$("authMsg").textContent=e.message}};
async function boot(){if(!token)return;if(!await api("/api/me").then(d=>(me=d.user,true)).catch(()=>false)){localStorage.removeItem("luka_token");token=null;return}$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("account").innerHTML=esc(me.displayName)+' <button id="logout">ログアウト</button>';$("logout").onclick=()=>{localStorage.removeItem("luka_token");location.reload()};$("badge").textContent=me.isAdmin?"ADMIN":"";document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>showPage(b.dataset.page));await loadSpaces();showPage("home");refreshCounts()}
async function loadSpaces(){spaces=(await api("/api/spaces")).spaces;$("spaces").innerHTML=spaces.length?spaces.map(s=>`<button class="space" data-id="${s.id}">${esc(s.name)}</button>`).join(""):"<small>まだありません</small>";document.querySelectorAll(".space").forEach(b=>b.onclick=()=>spacePage(b.dataset.id))}
async function spacePage(id){let s=spaces.find(x=>x.id===id);$("title").textContent=s.name;$("subtitle").textContent="スペース";$("page").innerHTML=`<div class="rooms">${s.rooms.map(r=>`<button class="room" data-id="${r.id}"># ${esc(r.name)}</button>`).join("")}</div><div id="messages" class="messages"><div class="empty">部屋を選択してください</div></div><form id="composer"><input id="msg" placeholder="メッセージを入力…"><button class="primary">送信</button></form>`;document.querySelectorAll(".room").forEach(b=>b.onclick=()=>roomPage(s,b.dataset.id));}
async function roomPage(s,rid){currentRoom=s.rooms.find(r=>r.id===rid);$("title").textContent=s.name;$("subtitle").textContent="# "+currentRoom.name;let d=await api("/api/rooms/"+rid+"/messages").catch(()=>({messages:[]}));$("page").innerHTML=`<div id="messages" class="messages"></div><form id="composer"><input id="msg" placeholder="メッセージを入力…"><button class="primary">送信</button></form>`;renderMsgs(d.messages);$("composer").onsubmit=async e=>{e.preventDefault();let b=$("msg").value.trim();if(!b)return;await api("/api/rooms/"+rid+"/messages",{method:"POST",body:JSON.stringify({body:b})});$("msg").value=""};socket.emit("joinRoom",rid)}
function renderMsgs(ms){$("messages").innerHTML=ms.length?ms.map(m=>`<article><small>${esc(m.userId)}・${new Date(m.createdAt).toLocaleString("ja-JP")}</small><div>${esc(m.body)}</div></article>`).join(""):'<div class="empty">まだメッセージはありません。</div>'}
function showPage(p){page=p;document.querySelectorAll(".navbtn").forEach(b=>b.classList.toggle("active",b.dataset.page===p));if(p==="home"){ $("title").textContent="ホーム";$("subtitle").textContent="Luka Web";$("page").innerHTML=`<div class="welcome"><h2>ようこそ、${esc(me.displayName)}さん！</h2><p>左のメニューからDM、フレンド、通知、プロフィールを開けます。</p></div>`}if(p==="dm")renderDM();if(p==="friends")renderFriends();if(p==="notifications")renderNotifications();if(p==="profile")renderProfile()}
async function renderDM(){let d=await api("/api/dms");$("title").textContent="DM";$("subtitle").textContent="フレンドと直接話す";$("page").innerHTML=`<div class="split"><div><h3>DM一覧</h3><div id="dmList">${d.rooms.map(r=>`<button class="listbtn" data-rid="${r.id}">${esc(r.user.displayName)}</button>`).join("")}</div><button id="newDM" class="secondary">＋ 新しいDM</button></div><div id="dmPanel" class="panel">DMを選択してください</div></div>`;d.rooms.forEach(r=>document.querySelector(`[data-rid="${r.id}"]`).onclick=()=>openDM(r));$("newDM").onclick=async()=>{let u=prompt("相手のユーザーIDを入力");if(!u)return;try{let r=await api("/api/dms",{method:"POST",body:JSON.stringify({userId:u})});openDM(r)}catch(e){alert(e.message)}}}
async function openDM(r){let d=await api("/api/dms/"+r.id+"/messages");$("dmPanel").innerHTML=`<h3>${esc(r.user.displayName)}</h3><div id="dmMsgs" class="messages"></div><form id="dmForm"><input id="dmInput" placeholder="メッセージ…"><button class="primary">送信</button></form>`;$("dmMsgs").innerHTML=d.messages.map(m=>`<article class="${m.userId===me.id?"mine":""}">${esc(m.body)}<small>${new Date(m.createdAt).toLocaleString("ja-JP")}</small></article>`).join("");socket.emit("joinRoom",r.id);$("dmForm").onsubmit=async e=>{e.preventDefault();let b=$("dmInput").value.trim();if(!b)return;await api("/api/dms/"+r.id+"/messages",{method:"POST",body:JSON.stringify({body:b})});$("dmInput").value=""}}
async function renderFriends(){let [f,req]=await Promise.all([api("/api/friends"),api("/api/friend-requests")]);$("title").textContent="フレンド";$("subtitle").textContent="つながりを管理";$("page").innerHTML=`<div class="search"><input id="userSearch" placeholder="ユーザー名で検索"><button id="searchBtn" class="primary">検索</button></div><div id="searchResults"></div><h3>フレンド</h3><div>${f.friends.map(u=>`<div class="friend">${esc(u.displayName)} <small>@${esc(u.username)}</small><button onclick="startDM('${u.id}')">DM</button></div>`).join("")||"まだフレンドはいません。"}</div><h3>届いた申請</h3><div>${req.incoming.map(r=>`<div class="friend">${esc(r.from)} <button onclick="friendAction('${r.id}','accept')">承認</button><button onclick="friendAction('${r.id}','reject')">拒否</button></div>`).join("")||"ありません。"}</div>`;$("searchBtn").onclick=async()=>{let x=await api("/api/users/search?q="+encodeURIComponent($("userSearch").value));$("searchResults").innerHTML=x.users.map(u=>`<div class="friend"><b>${esc(u.displayName)}</b> <small>@${esc(u.username)}</small><button onclick="sendFriend('${u.id}')">申請</button></div>`).join("")||"見つかりませんでした。"}}
window.sendFriend=async id=>{try{await api("/api/friend-requests",{method:"POST",body:JSON.stringify({userId:id})});alert("申請しました！")}catch(e){alert(e.message)}};window.friendAction=async(id,a)=>{await api("/api/friend-requests/"+id,{method:"POST",body:JSON.stringify({action:a})});renderFriends();};window.startDM=async id=>{let r=await api("/api/dms",{method:"POST",body:JSON.stringify({userId:id})});showPage("dm");setTimeout(()=>openDM(r),100)};
async function renderNotifications(){let d=await api("/api/notifications");$("title").textContent="通知";$("subtitle").textContent="お知らせ";$("page").innerHTML=`<button id="readAll" class="secondary">すべて既読</button><div class="notifications">${d.notifications.map(n=>`<article class="${n.readAt?"read":""}"><b>${esc(n.title)}</b><div>${esc(n.body)}</div><small>${new Date(n.createdAt).toLocaleString("ja-JP")}</small></article>`).join("")||"通知はありません。"}</div>`;$("readAll").onclick=async()=>{await api("/api/notifications/read-all",{method:"POST"});renderNotifications();refreshCounts()}}
async function renderProfile(){let d=await api("/api/me");$("title").textContent="プロフィール";$("subtitle").textContent="@"+d.user.username;$("page").innerHTML=`<div class="profile"><div class="avatar">${esc((d.user.displayName||"?")[0])}</div><input id="displayName" value="${esc(d.user.displayName)}" placeholder="表示名"><textarea id="bio" placeholder="自己紹介">${esc(d.user.bio)}</textarea><button id="saveProfile" class="primary">保存</button></div>`;$("saveProfile").onclick=async()=>{await api("/api/me",{method:"PATCH",body:JSON.stringify({displayName:$("displayName").value,bio:$("bio").value})});alert("保存しました");boot()}}
async function refreshCounts(){try{let n=await api("/api/notifications");$("notCount").textContent=n.notifications.filter(x=>!x.readAt).length||"";let d=await api("/api/dms");$("dmCount").textContent=d.rooms.length||""}catch{}}
$("newSpace").onclick=async()=>{let n=prompt("スペース名");if(n){await api("/api/spaces",{method:"POST",body:JSON.stringify({name:n})});loadSpaces()}};socket.on("dmMessage",()=>refreshCounts());boot();