-- Luka Web v3.0 PostgreSQL/Supabase target schema
create table if not exists profiles(id uuid primary key,username text unique not null,display_name text not null,bio text not null default '',account_type text not null default 'user',is_admin boolean not null default false,created_at timestamptz not null default now());
create table if not exists spaces(id uuid primary key,name text not null,description text not null default '',owner_id uuid not null references profiles(id),invite_only boolean not null default true,created_at timestamptz not null default now());
create table if not exists space_members(space_id uuid references spaces(id) on delete cascade,user_id uuid references profiles(id) on delete cascade,role text not null default 'member',joined_at timestamptz not null default now(),primary key(space_id,user_id));
create table if not exists rooms(id uuid primary key,space_id uuid not null references spaces(id) on delete cascade,name text not null,created_at timestamptz not null default now());
create table if not exists messages(id uuid primary key,room_id uuid not null references rooms(id) on delete cascade,user_id uuid not null references profiles(id),body text not null,reply_to uuid references messages(id),created_at timestamptz not null default now(),edited_at timestamptz,deleted_at timestamptz);
create index if not exists messages_room_created_idx on messages(room_id,created_at);
create table if not exists message_reactions(message_id uuid references messages(id) on delete cascade,user_id uuid references profiles(id) on delete cascade,reaction text not null,created_at timestamptz not null default now(),primary key(message_id,user_id,reaction));
create table if not exists message_pins(message_id uuid primary key references messages(id) on delete cascade,pinned_by uuid not null references profiles(id),pinned_at timestamptz not null default now());
create table if not exists friend_requests(id uuid primary key,from_user_id uuid not null references profiles(id) on delete cascade,to_user_id uuid not null references profiles(id) on delete cascade,status text not null default 'pending',created_at timestamptz not null default now());
create table if not exists friendships(user_a uuid references profiles(id) on delete cascade,user_b uuid references profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_a,user_b));
create table if not exists blocks(blocker_id uuid references profiles(id) on delete cascade,blocked_id uuid references profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(blocker_id,blocked_id));
create table if not exists notifications(id uuid primary key,user_id uuid not null references profiles(id) on delete cascade,type text not null,title text not null,body text not null,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists reports(id uuid primary key,reporter_id uuid references profiles(id),target_user_id uuid references profiles(id),message_id uuid references messages(id),reason text not null,status text not null default 'open',created_at timestamptz not null default now(),resolved_at timestamptz);
create table if not exists invites(id uuid primary key,space_id uuid not null references spaces(id) on delete cascade,code text unique not null,created_by uuid not null references profiles(id),expires_at timestamptz,created_at timestamptz not null default now());
create table if not exists files(id uuid primary key,uploader_id uuid not null references profiles(id),space_id uuid references spaces(id) on delete cascade,room_id uuid references rooms(id) on delete cascade,message_id uuid references messages(id) on delete cascade,storage_path text not null,original_name text not null,mime_type text not null,size_bytes bigint not null,created_at timestamptz not null default now());
-- Presence/typing are ephemeral and should not be permanently stored. Admin mode must not receive presence data.
