const express=require("express"),http=require("http"),path=require("path"),fs=require("fs"),crypto=require("crypto"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),{Server}=require("socket.io");
const app=express(),server=http.createServer(app),io=new Server(server),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"CHANGE_THIS_IN_PRODUCTION",DATA=path.join(__dirname,"luka.json");
app.use(express.json({limit:"2mb"}));app.use(express.static(__dirname));
function base(){return{version:3,users:[],spaces:[],rooms:[],messages:[],friends:[],friendRequests:[],dmRooms:[],dmMessages:[],notifications:[],reports:[],blocks:[],invites:[],reactions:[],pins:[]}}
function load(){if(!fs.existsSync(DATA))return base();try{let d=JSON.parse(fs.readFileSync(DATA));let b=base();for(let k of Object.keys(b))if(!(k in d))d[k]=b[k];d.version=3;return d}catch{return base()}}
let db=load();const save=()=>{let t=DATA+".tmp";fs.writeFileSync(t,JSON.stringify(db,null,2));fs.renameSync(t,DATA)},id=p=>p+"_"+crypto.randomBytes(8).toString("hex");
const pub=u=>({id:u.id,username:u.username,displayName:u.displayName||u.username,bio:u.bio||"",avatar:u.avatar||"",accountType:u.accountType||"user",isAdmin:!!u.isAdmin,createdAt:u.createdAt});
function auth(req,res,next){let h=req.headers.authorization||"",t=h.startsWith("Bearer ")?h.slice(7):"";if(!t)return res.status(401).json({error:"ログインが必要です"});try{let p=jwt.verify(t,SECRET),u=db.users.find(x=>x.id===p.uid);if(!u)throw 0;req.user=u;next()}catch{res.status(401).json({error:"セッションが無効です"})}}
function admin(req,res,next){if(!req.user.isAdmin&&req.user.accountType!=="admin")return res.status(403).json({error:"管理者権限が必要です"});next()}
app.get("/",(q,s)=>s.sendFile(path.join(__dirname,"index.html")));app.get("/health",(q,s)=>s.json({ok:true,version:"3.1.0"}));

app.post("/api/auth/register",async(q,s)=>{let u=String(q.body.username||"").trim(),p=String(q.body.password||"");if(!/^[A-Za-z0-9_]{3,24}$/.test(u))return s.status(400).json({error:"ユーザー名は3〜24文字の英数字・_で入力してください"});if(p.length<8)return s.status(400).json({error:"パスワードは8文字以上にしてください"});if(db.users.some(x=>x.username.toLowerCase()===u.toLowerCase()))return s.status(409).json({error:"そのユーザー名は使用されています"});let x={id:id("usr"),username:u,displayName:u,bio:"",avatar:"",passwordHash:await bcrypt.hash(p,12),accountType:"user",isAdmin:!db.users.some(x=>x.isAdmin),createdAt:new Date().toISOString()};db.users.push(x);save();s.json({token:jwt.sign({uid:x.id},SECRET,{expiresIn:"30d"}),user:pub(x)})});
app.post("/api/auth/login",async(q,s)=>{let u=String(q.body.username||"").trim(),p=String(q.body.password||""),x=db.users.find(x=>x.username.toLowerCase()===u.toLowerCase());if(!x)return s.status(401).json({error:"ユーザー名またはパスワードが違います"});let ok=x.passwordHash?await bcrypt.compare(p,x.passwordHash):false;if(!ok)return s.status(401).json({error:"ユーザー名またはパスワードが違います"});s.json({token:jwt.sign({uid:x.id},SECRET,{expiresIn:"30d"}),user:pub(x)})});
app.get("/api/me",auth,(q,s)=>s.json({user:pub(q.user)}));
app.patch("/api/me",auth,(q,s)=>{q.user.displayName=String(q.body.displayName??q.user.displayName).trim().slice(0,40)||q.user.username;q.user.bio=String(q.body.bio??q.user.bio).slice(0,300);q.user.avatar=String(q.body.avatar??q.user.avatar).slice(0,500);save();s.json({user:pub(q.user)})});
app.get("/api/users/search",auth,(q,s)=>{let x=String(q.query.q||"").trim().toLowerCase();if(!x)return s.json({users:[]});s.json({users:db.users.filter(u=>u.id!==q.user.id&&(u.username.toLowerCase().includes(x)||(u.displayName||"").toLowerCase().includes(x))).slice(0,30).map(pub)})});

function areFriends(a,b){return db.friends.some(f=>(f.a===a&&f.b===b)||(f.a===b&&f.b===a))}
app.get("/api/friends",auth,(q,s)=>s.json({friends:db.friends.filter(f=>f.a===q.user.id||f.b===q.user.id).map(f=>pub(db.users.find(u=>u.id===(f.a===q.user.id?f.b:f.a)))).filter(Boolean)}));
app.get("/api/friend-requests",auth,(q,s)=>s.json({incoming:db.friendRequests.filter(r=>r.to===q.user.id&&r.status==="pending"),outgoing:db.friendRequests.filter(r=>r.from===q.user.id&&r.status==="pending")}));
app.post("/api/friend-requests",auth,(q,s)=>{let to=String(q.body.userId||"");if(!db.users.some(u=>u.id===to)||to===q.user.id)return s.status(400).json({error:"ユーザーが見つかりません"});if(areFriends(q.user.id,to))return s.status(400).json({error:"すでにフレンドです"});if(db.friendRequests.some(r=>r.from===q.user.id&&r.to===to&&r.status==="pending"))return s.status(400).json({error:"申請済みです"});let r={id:id("fr"),from:q.user.id,to,status:"pending",createdAt:new Date().toISOString()};db.friendRequests.push(r);db.notifications.push({id:id("not"),userId:to,type:"friend_request",title:"フレンド申請",body:q.user.displayName+"さんからフレンド申請が届きました。",createdAt:new Date().toISOString(),readAt:null});save();s.json({request:r})});
app.post("/api/friend-requests/:rid",auth,(q,s)=>{let r=db.friendRequests.find(r=>r.id===q.params.rid&&r.to===q.user.id&&r.status==="pending");if(!r)return s.status(404).json({error:"申請がありません"});let accept=q.body.action==="accept";r.status=accept?"accepted":"rejected";if(accept)db.friends.push({a:r.from,b:r.to,createdAt:new Date().toISOString()});db.notifications.push({id:id("not"),userId:r.from,type:"friend_result",title:accept?"フレンド承認":"フレンド申請",body:q.user.displayName+"さんが申請を"+(accept?"承認":"拒否")+"しました。",createdAt:new Date().toISOString(),readAt:null});save();s.json({ok:true})});
app.delete("/api/friends/:uid",auth,(q,s)=>{db.friends=db.friends.filter(f=>!((f.a===q.user.id&&f.b===q.params.uid)||(f.b===q.user.id&&f.a===q.params.uid)));save();s.json({ok:true})});
app.post("/api/blocks/:uid",auth,(q,s)=>{if(q.params.uid===q.user.id)return s.status(400).json({error:"自分はブロックできません"});if(!db.blocks.some(b=>b.a===q.user.id&&b.b===q.params.uid))db.blocks.push({a:q.user.id,b:q.params.uid,createdAt:new Date().toISOString()});save();s.json({ok:true})});

function dmRoom(a,b){return db.dmRooms.find(r=>(r.a===a&&r.b===b)||(r.a===b&&r.b===a))}
app.get("/api/dms",auth,(q,s)=>s.json({rooms:db.dmRooms.filter(r=>r.a===q.user.id||r.b===q.user.id).map(r=>({...r,user:pub(db.users.find(u=>u.id===(r.a===q.user.id?r.b:r.a)))}))}));
app.post("/api/dms",auth,(q,s)=>{let to=String(q.body.userId||""),u=db.users.find(u=>u.id===to);if(!u||to===q.user.id)return s.status(400).json({error:"ユーザーが見つかりません"});if(db.blocks.some(b=>(b.a===q.user.id&&b.b===to)||(b.a===to&&b.b===q.user.id)))return s.status(403).json({error:"この相手とはDMできません"});let r=dmRoom(q.user.id,to);if(!r){r={id:id("dm"),a:q.user.id,b:to,createdAt:new Date().toISOString()};db.dmRooms.push(r);save()}s.json({room:r,user:pub(u)})});
app.get("/api/dms/:rid/messages",auth,(q,s)=>{let r=db.dmRooms.find(r=>r.id===q.params.rid&&(r.a===q.user.id||r.b===q.user.id));if(!r)return s.status(404).json({error:"DMがありません"});s.json({messages:db.dmMessages.filter(m=>m.roomId===r.id).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)).slice(-200)})});
app.post("/api/dms/:rid/messages",auth,(q,s)=>{let r=db.dmRooms.find(r=>r.id===q.params.rid&&(r.a===q.user.id||r.b===q.user.id));if(!r)return s.status(404).json({error:"DMがありません"});let to=r.a===q.user.id?r.b:r.a;if(db.blocks.some(b=>(b.a===q.user.id&&b.b===to)||(b.a===to&&b.b===q.user.id)))return s.status(403).json({error:"この相手とはDMできません"});let body=String(q.body.body||"").trim().slice(0,4000);if(!body)return s.status(400).json({error:"本文を入力してください"});let m={id:id("dmm"),roomId:r.id,userId:q.user.id,body,createdAt:new Date().toISOString()};db.dmMessages.push(m);db.notifications.push({id:id("not"),userId:to,type:"dm",title:"新しいDM",body:q.user.displayName+"さんからメッセージが届きました。",createdAt:new Date().toISOString(),readAt:null});save();io.to(r.id).emit("dmMessage",m);s.json({message:m})});

app.get("/api/notifications",auth,(q,s)=>s.json({notifications:db.notifications.filter(n=>n.userId===q.user.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,100)}));
app.post("/api/notifications/read-all",auth,(q,s)=>{db.notifications.filter(n=>n.userId===q.user.id).forEach(n=>n.readAt=n.readAt||new Date().toISOString());save();s.json({ok:true})});

app.get("/api/admin/reports",auth,admin,(q,s)=>s.json({reports:db.reports}));app.patch("/api/admin/reports/:rid",auth,admin,(q,s)=>{let r=db.reports.find(x=>x.id===q.params.rid);if(!r)return s.status(404).json({error:"通報がありません"});r.status=q.body.status==="resolved"?"resolved":"open";save();s.json({report:r})});

io.on("connection",socket=>{socket.on("joinRoom",r=>typeof r==="string"&&socket.join(r));socket.on("leaveRoom",r=>typeof r==="string"&&socket.leave(r));socket.on("typing",p=>{if(p?.roomId)socket.to(p.roomId).emit("typing",{roomId:p.roomId,userId:p.userId||null})})});
server.listen(PORT,"0.0.0.0",()=>console.log("Luka Web v3.1:",PORT));